services:
  - type: web
    name: printer-app
    env: docker
    repo: https://github.com/CSU-ITCapstone/Group-2.git
    branch: main
    buildCommand: dotnet publish --configuration Release --output out
